### PR TITLE
Make exception clearer

### PR DESCRIPTION
**Pull request by xenoterracide**
# What problem does this pull request solve?
Impossible to debug without a debugger, this should make it possible.

# Please provide any additional information below.

### CODE REVIEW

**Comment by jqno** [comment]
Thanks for the PR! I don't understand though, in what kind of scenario would this be a hard to debug problem?

You pass two parameters to `withPrefabValues`, one of them is null, and EV throws immediately. If it's difficult to decide which of the two was null, that seems to me to be more a problem in the surrounding test code than in EqualsVerifier itself...

Also, the Travis build fails on this PR.

**Comment by xenoterracide** [comment]
not so much "hard" to debug as "annoying", I don't really want to have to rerun a test in a debugger to tell me which of 2 values is null, especially if it fails first in CI. Really I'm just facilitating my own laziness.

 As far as CI I can fix it if you want, I edited in the GH editor.

**Comment by jqno** [comment]
But how do you end up in a situation where you can even pass a null in the first place?

I mean, you have two constants prepared somewhere, you pass them to `withPrefabValues`, you're done. Why would they be null, and even if they were, how would that not be immediately obvious?

**Comment by xenoterracide** [comment]
```
    @Test
    public void equivalence() {
        Organization red = mbf.payer().get();
        Organization black = mbf.payer().get();

        ClassificationTestEntityBuilder classification = mbf.classification();
        EqualsVerifier.forClass( ClassificationVisibility.class )
                .withIgnoredFields(  ID, "lockIncrement", "dateModified", "dateCreated" )
                .withRedefinedSuperclass()
                .withPrefabValues( OrganizationSettings.class, red.getSettings(), black.getSettings() )
                .withPrefabValues( Classification.class, classification.mdx().get(), classification.misc().get() )
                .verify();
    }
```

factory methods, or rather our mbf ( short for `ModelBuilderFactory` but probably should have been `ModelBuilderServiceLocator` ), I think it happened when I was trying to build something more complex than this and what was more fun, I ran into a scenario where org had a settings, but settings did not have its parent org.

< chasing ancient bugs trying to get the new thing to pass :/ I actually did get it to pass and fixed the objects I needed to, just filing bugs that I think would make it easier to debug.

**Comment by jqno** [comment]
So, basically what you're saying is you use a factory which, apparently, leaves some values null, deep inside the objects it creates? But I see your point now.

To be honest, I'd rather have separate messages that say "the red object is null" and "the black object is null". Maybe even one that says "both objects are null", if you're feeling ambitious. If you make that, add a few unit tests, and make sure the build passes (which you can test locally with `mvn verify`), I'll merge your PR.

**Comment by xenoterracide** [comment]
> So, basically what you're saying is you use a factory which, apparently, leaves some values null, deep inside the objects it creates? But I see your point now.

yes potentially, it's supposed to initialize objects to a "correct" state, e.g. could happen in production. That said, it's much newer and it may not, and as with all code, bugs can happen, I don't actually think it's the one that I pasted that failed, but a different one where I actually had to tweak something, possibly the one I threw away because I got tired of chasing the recursive nature of the structure, and it's not currently the thing I'm tasked with doing.

> If you make that, add a few unit tests, and make sure the build passes (which you can test locally with mvn verify), I'll merge your PR.

maybe this weekend, no promises ;)

**Comment by jqno** [comment]
Looks like this PR has gone stale, so I'm closing. If not, please feel free to re-open!

**Pull request closed without merging**
