### PR TITLE
add GitHub Actions CI

### PR DESCRIPTION
**Pull request by sullis**
# What problem does this pull request solve?

# Please provide any additional information below.

### CODE REVIEW

**Comment by jqno** [comment]
Thanks, but EqualsVerifier already has a pretty extensive CI over at CircleCI, which also checks Early Access versions of Java in various ways. What's the gain in having an additional set of CI checks on GitHub Actions as well?

**Comment by sullis** [comment]
I have converted projects from TravisCI to GitHub Actions because the builds run faster.

I cannot say what the actual performance will be for the [equalsverifier] project.  I was hoping to enable it so that we can inspect the actual build time.

**Comment by jqno** [comment]
I'm sorry, I don't have a lot of time to spend on migrating to Github Actions, especially since I already spent quite some time last year (unfortunately just before Github Actions was announced) migrating everything away from TravisCI to CircleCI, exactly for the same reasons you mention.
There's a link to CircleCI right on top of the project's readme where you can see the current build times; can you point me to a place where I can see the build times for Github Actions? I can't imagine that they would be very far apart but I'm willing to keep an open mind :).
Also, EqualsVerifier has a reasonably complicated workflow in CircleCI, would it be possible to migrate all of that to Actions as well?

**Comment by sullis** [comment]
Closing. The existing workflow is complicated.

**Pull request closed without merging**
