### PR TITLE
Upgrade to ByteBuddy 1.9.1

### PR DESCRIPTION
**Pull request by don-vip**
# What problem does this pull request solve?
- Upgrade to ByteBuddy 1.9.1. It contains fixes for Java 12, maybe it can help for #209 (not checked)
- Fixes to make Checkstyle happy

### CODE REVIEW

**Comment by jqno** [comment]
Hi Vincent! Thanks for the PR.

I've (manually) merged the version update, but not the checkstyle changes. When IntelliJ organises the imports, it leaves them the way they were in master, so I've spent some effort setting up Checkstyle so it supports that layout. (I don't want to go back and manually edit my imports all the time.) It took a little effort, as you can see here: https://github.com/checkstyle/checkstyle/issues/5510 :)

By the way, while I appreciate your PR's very much, you don't need to send one when Byte Buddy updates. I usually update all dependencies before I release EqualsVerifier anyway, and Byte Buddy releases much more often than I do :).

**Comment by jqno** [comment]
Or would you like a release with this new version of Byte Buddy? Because in that case, I can do that of course.

I'm not sure if it will help with #209 though, because the problem there has to do with annotations which I process with ASM, not Byte Buddy.

**Comment by don-vip** [comment]
OK no problem :)
The checkstyle fixes were needed to have a successful build with `mvn clean verify`. Does it work for you without the line breaks in imports?

**Comment by jqno** [comment]
Hm, that's strange. Yeah, I run `mvn clean verify` all the time and it works just fine. Same on Travis CI for several different versions of Java. I wonder what's different in your environment... 🤔

**Comment by don-vip** [comment]
Probably the version of Maven. I'm using 3.5.4

**Comment by jqno** [comment]
I also use Maven 3.5.4 😄

**Comment by don-vip** [comment]
OK I'll investigate further :)

**Pull request closed without merging**
